### ISSUE TITLE
Question: Does this track subdomain events?

### ISSUE THREAD

**Issue by diwu1989** [unstoppabledomains/resolution-service#60]
Let's say that i mint a nft domain: foobar.nft
And I then mint a subdomain: xyz.foobar.nft

Does this resolution service pick up on the subdomain?

**Comment by DancingAxolotl** [comment]
Hey @diwu1989!
Subdomains are not supported by the resolution service.

**Comment by sammyluo** [comment]
Closing this issue since it's been stale for a while.
